package com.schoolerp.school_erp.controller;

import com.schoolerp.school_erp.dto.PaymentOrderRequest;
import com.schoolerp.school_erp.dto.PaymentOrderResponse;
import com.schoolerp.school_erp.entity.PaymentOrder;
import com.schoolerp.school_erp.entity.User;
import com.schoolerp.school_erp.enums.RoleType;
import com.schoolerp.school_erp.repository.UserRepository;
import com.schoolerp.school_erp.service.PaymentService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

/**
 * Controller to handle payment checkout session initialization and gateway verification.
 * 
 * Constraints:
 * - Secured under "/api/payments/**", requiring a valid authentication token.
 * - Requires X-Tenant-ID header to resolve database tenant context.
 */
@RestController
@RequestMapping("/api/payments")
public class PaymentController {

    @Autowired
    private PaymentService paymentService;

    @Autowired
    private UserRepository userRepository;

    /**
     * Initiates a payment checkout session for student fees.
     * 
     * Constraints:
     * - Requires standard JWT in Authorization header.
     * - Requires X-Tenant-ID header.
     * - Requires X-User-ID header identifying the buyer.
     * - Role Restriction: The user identified by X-User-ID must exist and have one of the roles:
     *   SUPER_ADMIN, ADMIN, STUDENT, or PARENT.
     * - Request body must be valid and conform to PaymentOrderRequest.
     * 
     * @param request checkout configuration payload containing invoice/fee items details
     * @param customerUserId the ID of the customer (user) initiating the payment
     * @return payment session/order details for checkout integration
     */
    @PostMapping("/checkout")
    public ResponseEntity<?> createCheckoutSession(
            @Valid @RequestBody PaymentOrderRequest request,
            @RequestHeader("X-User-ID") UUID customerUserId) {

        User user = userRepository.findById(customerUserId)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));

        boolean isAuthorized = user.getRoles().stream().anyMatch(role -> 
            role.getName().equalsIgnoreCase("SUPER_ADMIN") || 
            role.getName().equalsIgnoreCase("ADMIN") || 
            role.getName().equalsIgnoreCase("STUDENT") || 
            role.getName().equalsIgnoreCase("PARENT")
        );

        if (!isAuthorized) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN)
                    .body("Unauthorized: Only Students, Parents, or Admins can make payments.");
        }

        PaymentOrderResponse response = paymentService.createPaymentOrder(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Verifies the payment transaction status with the payment gateway.
     * 
     * Constraints:
     * - Requires standard JWT in Authorization header.
     * - Requires X-Tenant-ID header.
     * - Expects gatewayOrderId, gatewayPaymentId, and status as request parameters.
     * 
     * @param gatewayOrderId payment order identifier generated by the gateway
     * @param gatewayPaymentId payment transaction identifier generated by the gateway
     * @param status payment status status from the gateway
     * @return updated payment order status information
     */
    @PostMapping("/verify")
    public ResponseEntity<PaymentOrder> verifyPayment(
            @RequestParam String gatewayOrderId,
            @RequestParam String gatewayPaymentId,
            @RequestParam String status) {

        PaymentOrder response = paymentService.verifyPayment(gatewayOrderId, gatewayPaymentId, status);
        return ResponseEntity.ok(response);
    }
}
